## 얼굴 인식

In [1]:
import cv2
import numpy as np

In [9]:
path ='images/nmixx.webp'


In [11]:
face_cascade = cv2.CascadeClassifier('cascade/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('cascade/haarcascade_eye.xml')
img = cv2.imread(path)
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale2(
        img_gray, scaleFactor=1.1, minNeighbors=5, minSize=(20, 20)
    )
eyes = eye_cascade.detectMultiScale(img_gray,1.1,4)
print(faces)

(array([[761,  89,  86,  86],
       [569,  76, 128, 128],
       [281,  58, 158, 158],
       [139,  71, 146, 146],
       [414,  61, 161, 161],
       [731, 322,  51,  51]], dtype=int32), array([16, 64, 49, 25, 13,  7], dtype=int32))


In [10]:
face_cascade = cv2.CascadeClassifier('cascade/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('cascade/haarcascade_eye.xml')
img = cv2.imread(path)
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale2(
        img_gray, scaleFactor=1.1, minNeighbors=5, minSize=(20, 20)
    )
eyes = eye_cascade.detectMultiScale(img_gray,1.1,4)
print(faces)
for (x,y,w,h) in faces:
    img = cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),3)
if len(eyes):
    for (x,y,w,h) in eyes:
        img = cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),3)
cv2.imshow('face',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

ValueError: too many values to unpack (expected 4)

In [2]:
video = 'video/face.mp4'
cap = cv2.VideoCapture(video)
face_cascade = cv2.CascadeClassifier('cascade/haarcascade_frontalface_default.xml')
if not cap.isOpened():
    exit()
while True:
    ret, frame = cap.read()
    
    frame_gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    faces, weights_face= face_cascade.detectMultiScale2(
        frame_gray, scaleFactor=1.1, minNeighbors=5, minSize=(20, 20)
    )
    print(faces,weights_face)
    if not ret:
        break
    for (x,y,w,h) in faces:
        frame = cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,0),3)
    
    cv2.imshow('camera',frame)
    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
cv2.waitKey(1)

[[964  78 882 882]] [47]
[[962  75 875 875]] [46]
[[964  78 851 851]] [46]
[[951  75 861 861]] [44]
[[944  75 869 869]] [42]


2025-01-08 10:48:52.514 Python[66294:32485217] +[IMKClient subclass]: chose IMKClient_Modern
2025-01-08 10:48:52.514 Python[66294:32485217] +[IMKInputSession subclass]: chose IMKInputSession_Modern


[[934  64 879 879]] [43]
[[935  70 857 857]] [44]
[[917  68 871 871]] [43]
[[920  69 861 861]] [49]
[[908  68 884 884]] [45]
[[909  75 865 865]] [41]
[[895  69 874 874]] [41]
[[898  68 885 885]] [43]
[[897  84 872 872]] [44]
[[889  81 886 886]] [45]
[[872  82 917 917]] [47]
[[877  87 925 925]] [55]
[[868 101 917 917]] [48]
[[861 109 923 923]] [50]
[[854 114 938 938]] [57]
[[863 119 931 931]] [53]
[[883 127 914 914]] [51]
[[880 132 911 911]] [55]
[[880 131 910 910]] [51]
[[884 123 927 927]] [57]
[[876 110 950 950]] [53]
[[895 107 944 944]] [47]
[[914 117 913 913]] [50]
[[923 114 898 898]] [51]
[[927 102 922 922]] [53]
[[939  93 915 915]] [43]
[[960  91 908 908]] [45]
[[971  87 907 907]] [48]
[[976  93 905 905]] [63]
[[999  89 893 893]] [56]
[[1008   84  902  902]] [53]
[[1022   80  891  891]] [46]
[[1044   86  888  888]] [48]
[[1037   76  920  920]] [49]
[[1051   82  893  893]] [55]
[[1072   83  890  890]] [47]
[[1072   69  918  918]] [45]
[[1087   69  907  907]] [45]
[[1082   74  919  

-1

## 실습 - 캠 얼굴 인식

In [2]:
cap = cv2.VideoCapture(0)
face_cascade = cv2.CascadeClassifier('cascade/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('cascade/haarcascade_eye.xml')
if not cap.isOpened():
    exit()
while True:
    ret, frame = cap.read()
    if not ret:
        break
    frame_gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(frame_gray,1.3,10)
    
    eyes = eye_cascade.detectMultiScale(frame_gray,1.1,8)
    for (x,y,w,h) in faces:
        frame = cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,0),3)
        frame = cv2.putText(frame, "face", ((2*x+w)//2,y), cv2.FONT_HERSHEY_SIMPLEX, 2, (255,0,0),3)
    for (x,y,w,h) in eyes:
        frame = cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),3)
        frame = cv2.putText(frame, "eye", ((2*x+w)//2,y), cv2.FONT_HERSHEY_SIMPLEX, 
             2, (255,0,0),3)
    cv2.imshow('camera',frame)
    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
cv2.waitKey(1)

2025-01-08 11:14:16.449 Python[67449:32509205] +[IMKClient subclass]: chose IMKClient_Modern
2025-01-08 11:14:16.449 Python[67449:32509205] +[IMKInputSession subclass]: chose IMKInputSession_Modern
2025-01-08 11:14:20.158 Python[67449:32509205] error messaging the mach port for IMKCFRunLoopWakeUpReliable


-1

In [ ]:
cap = cv2.VideoCapture(0)

face_cascade = cv2.CascadeClassifier('cascade/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('cascade/haarcascade_eye.xml')
if not cap.isOpened():
    exit()
while True:
    ret, frame = cap.read()
    if not ret:
        break
    frame_gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    faces, weights_face= face_cascade.detectMultiScale2(
        frame_gray, scaleFactor=1.1, minNeighbors=5, minSize=(20, 20)
    )
    eyes,weights_eye = eye_cascade.detectMultiScale2(frame_gray, scaleFactor=1.1, minNeighbors=5, minSize=(20, 20)
    )
    
    for (face,weight) in zip(faces,weights_face):
        x,y,w,h = face
        
        frame = cv2.putText(frame, f"face, score: {weight}", ((2*x+w)//2,y), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,0,0),3)
    for (eye, weight) in zip(eyes,weights_eye):
        x,y,w,h = eye
        frame = cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),3)
        frame = cv2.putText(frame, f"eye, score :{weight}", ((2*x+w)//2,y), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,0,0),3)
    cv2.imshow('camera',frame)
    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
cv2.waitKey(1)

## 실습 2 사진

In [26]:
img = cv2.imread('images/nmixx.webp')
left = cv2.imread('images/left_eye.jpg')
right = cv2.imread('images/right_eye.jpg')
face_cascade = cv2.CascadeClassifier('cascade/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('cascade/haarcascade_eye.xml')

img_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
faces = face_cascade.detectMultiScale(img_gray,1.5,2)
eyes = eye_cascade.detectMultiScale(img_gray,1.5,1)
    
for x,y,w,h in faces:
    for x_e,y_e,w_e,h_e in eyes:
        if x <= x_e<= x+w and y <=y_e<=y+h: 
                if x_e < (x+w/2) :
                    dst_left = cv2.resize(left, (w_e, h_e), interpolation=cv2.INTER_LANCZOS4)
                    img[y_e:y_e+h_e,x_e:x_e+w_e] = dst_left
                else :
                    dst_right = cv2.resize(right, (w_e, h_e), interpolation=cv2.INTER_LANCZOS4)
                    img[y_e:y_e+h_e,x_e:x_e+w_e] = dst_right
cv2.imshow('camera',img)
    

cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

: 

## 웹캠 영상에 눈 붙이기

In [21]:
cap = cv2.VideoCapture(0)
left = cv2.imread('images/left_eye.jpg')
right = cv2.imread('images/right_eye.jpg')
face_cascade = cv2.CascadeClassifier('cascade/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('cascade/haarcascade_eye.xml')
if not cap.isOpened():
    exit()
while True:
    ret, frame = cap.read()
    if not ret:
        break
    frame_gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(frame_gray,1.3,10)
    eyes = eye_cascade.detectMultiScale(frame_gray,1.1,8)
    
    for x,y,w,h in faces:
        for x_e,y_e,w_e,h_e in eyes:
            if x <= x_e<= x+w and y <=y_e<=y+h:
                if x_e < (x+w/2) :
                    dst_left = cv2.resize(left, (w_e, h_e), interpolation=cv2.INTER_LANCZOS4)
                    frame[y_e:y_e+h_e,x_e:x_e+w_e] = dst_left
                else :
                    dst_right = cv2.resize(right, (w_e, h_e), interpolation=cv2.INTER_LANCZOS4)
                    frame[y_e:y_e+h_e,x_e:x_e+w_e] = dst_right
    cv2.imshow('camera',frame)
    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
cv2.waitKey(1)

-1